---
title: "Prompt engineering"
subtitle: "Day 2 - 9:00 AM - 9:30 AM"
date: 2026-07-14
date-modified: today
author:
  - name: Hannah Toth
    email: toth.302@osu.edu
    affiliation: 
      - name: Department of Plant Pathology, Ohio State University
        url: https://plantpath.osu.edu
title-slide-attributes:
  data-background-color: "silver"
format:
  revealjs:
    theme: [default, theme_mod.scss]
    css: ../slides.css
    smaller: true
    scrollable: false
    progress: true
    incremental: false
    slide-number: true
    slide-level: 2
    highlight-style: pygments
    embed-resources: false # Can't be used with chalkboard
    chalkboard:
      theme: whiteboard
    toc: true
    toc-depth: 1
    toc-title: TBD
    footer: "[~ Gen and agentic AI workshop ~](https://cfaes-bioinfo.github.io/agentic-ai-workshop/)"
    logo: ../img/CFAES-Horiz-RGBHEX.svg
    menu:
      width: wide
      numbers: true
editor_options: 
  chunk_output_type: console
bibliography: refs.bib # You can add reference to this files if you have and cite any
---

---------

<hr style="height:1pt; visibility:hidden;" />

::: {.callout-caution appearance="simple"}
**_This page is still subject to change_**
:::

<hr style="height:1pt; visibility:hidden;" />

## Introduction to Prompt Engineering
- **What is a prompt?**\
  - A prompt is the input text or query that you provide to an AI model to generate a response. It can be a question, statement, or instruction.
- **What is prompt engineering?**\
  - The process of designing and optimizing prompts to provide you relevant and accurate responses for your specific needs.


## Why is prompt engineering important?
- The only thing that stands in between **you** and an **effective solution** is the prompt you generate.

- there are entire jobs dedicated to prompt engineering <more on this later>

## Anatomy of a well-crafted prompt
These are the absolutely necessary, bare bone components that are apart of a well-crafted prompt:

- **Task**:

- **Context**:

- **Output Format**

## Optional, but potentially useful pieces to include in your prompt
**Role/Persona**
- Do you want your AI model to act as a scientist? a teacher? a programmer? a graduate student? If so, consider including changing your prompt from this:

to this:

## Let's practice prompt engineering
Boot up your favorite AI model and let's get started.


