---
title: "DIY with own (or other) data"
date: 2026-07-14
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
bibliography: refs.bib
---

---------

<hr style="height:1pt; visibility:hidden;" />

## Introduction

During this session, you will have the opportunity to work by yourself
with the tools that we have introduced during the workshop.

The instructors will be available to help you with any questions you may have.

- You can use your **own data** if you'd like.
  Let us know if you need any help with getting started, such as uploading your data.

- You can also continue working on the **example data**.
  We have a bit more info on that below.

::: callout-note
### Ask AI!
Remember that you can also ask AI ---including the Gemini options Jonathan showed---
to help brainstorm what to do!
Use this as an opportunity to explore the possibilities of AI in your own research context.
:::

::: callout-tip
### One or more plots as an end goal
Whichever data set you use, perhaps a nice end goal is to **create one or more plots**,
i.e. visualizations of your results.
Even if you, say, only align reads to a reference genome,
you can still make a plot of the alignment success statistics.
:::

::: callout-important
#### Keep the scope of your questions reasonable
Don't go overboard with very big asks,
especially ones far removed from research data analysis context that is the
focus of the this workshop.
For example, we don't really want to you to build a massive web app for personal use, here.
If you want to try something along those lines, please use your own API key.

If you're in doubt, please ask the instructors for guidance.
:::

## Working with the example dataset

Below are some suggestions if you'd like to continue working on the @iqbal2025 dataset.

- A core first goal of almost any RNA-Seq analysis is to produce a "count table",
  which has counts for each gene (a proxy for gene expression levels) for each sample.
  You can try to produce such a count table.
  If you're unsure about the steps needed to do this, you can start by asking AI!
  _(Your `CLAUDE.md` may already have some instructions for this.)_

  This can be done step-by-step with separate shell scripts,
  or for more advanced (or ambitious!) users,
  you can try to write a simple but reproducible Nextflow pipeline.

  ::: {.callout-tip appearance="simple"}
  If you're going to submit a bunch of Slurm jobs, including with `for` loops
  to loop over files or samples, you'll also want a separate file (shell script,
  or optionally Markdown file with code blocks) to store that code.
  As with everything else, you can ask AI to help you write that code and design
  the way to organize scripts.
  :::

- If you would prefer to start with more "downstream" analyses on the count table,
  such as making a PCA plot of expression profiles,
  doing differential expression analysis, making heatmaps, and so on.
  
  **There is a pre-made count table at**
  `/fs/scratch/PAS3454/share/iqbal_results/salmon.merged.gene_counts_length_scaled.tsv`

  ::: {.callout-note}
  ### Not sure what to do, exactly?

  - One option is to give Claude some context and ask it what to do!

  - You can also take a look at this tutorial page which goes over the typical
    steps of an RNA-Seq analysis:
    [RNA-Seq analysis tutorial](https://jelmerp.github.io/ENTMLGY6703/labs/DE.html).
    This is a different dataset, so don't try to follow the exact code ---
    use Claude to adapt it, or start from scratch.
  :::

#### Whole-genome resequencing data
If you'd like to work with the whole-genome resequencing data from this paper
instead of the RNA-Seq data,
this is available in `/fs/scratch/PAS3454/data/wgs_iqbal`.
