---
title: "DIY with own (or other) data"
date: 2026-07-03
date-modified: today
author:
  - name: Jelmer Poelstra
    orcid: 0000-0002-3514-7462
    email: poelstra.1@osu.edu
    affiliation: 
      - name: CFAES Bioinformatics Core, Ohio State University
        url: https://mcic.osu.edu/bioinformatics
bibliography: refs.bib # You can add reference to this files if you have and cite any
---

---------

<hr style="height:1pt; visibility:hidden;" />

::: {.callout-caution appearance="simple"}
**_This page is still subject to change_**
:::

<hr style="height:1pt; visibility:hidden;" />

## Introduction

During this session,

::: callout-tip
### One or more plots as an end goal
Whichever data set you use, perhaps a nice end goal is one or more plots.
Even if you, say, only align reads to a reference genome,
you can still make a plot of the alignment success statistics.
:::

::: callout-warning
#### Keep it reasonable
Don't go overboard with very big asks,
especially ones far removed from the omics data analysis context.
For example, we don't really want to you to build a massive web app for personal use, here.
If you want to try something along those lines, please use your own API key.
:::

## Example dataset

If you don't have your own data, we'd recommend that you continue working with
the example dataset.

- Pre-made count table 

If you want to continue working with the example dataset:

- Get it to help you run the Nextflow/nf-core rnaseq pipeline
- Write a simple but reproducible pipeline

