project:
  type: website
  output-dir: docs

website:
  title: "Agentic AI Workshop"
  favicon: img/favicon.png
  site-url: https://cfaes-bioinfo.github.io/agentic-ai-workshop/
  repo-url: https://github.com/cfaes-bioinfo/agentic-ai-workshop
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - text: Day 1
        menu:
          - text: "1: Intro to the workshop"
          - text: "2: Intro to Generative AI and LLMs"
          - text: "4: Use cases and tools for research"
          - text: "5: Toolset intro and setup"
            #href: 05-toolbox-setup.qmd
          - text: "7: Using GitHub Copilot and Claude Code"
            #href: 07-agentic1.qmd
      - text: Day 2
        menu:
          - text: "8: Prompt engineering"
          - text: "9: Advanced agentic options and skills"
          - text: "10: A worked example analysis with agents"
          - text: "11: Limitations and responsible use of AI"
          - text: "12: DIY with own (or other) data"
    right:
      - text: Pre-workshop learning
        menu:
          - text: "1: OSC intro"
            href: p1-osc-intro.qmd
          - text: "2: Unix shell basics"
            href: p2-shell-intro.qmd
          - text: "3: Command-line software"
            href: p3-cl-software.qmd
          - text: "4: Shell scripts and Slurm"
            href: p4-shell-scripts.qmd
          - text: "--------------"
          - text: "5: Optional self-study material"
            href: p5-homework.qmd
      - text: Pre-workshop setup
        menu:
          - text: OSC account setup
            href: s1-osc-account.qmd
          - text: VS Code installation
            href: s2-vscode-install.qmd
          - text: "--------------"
          - text: "Optional: GitHub account setup"
            href: s3-github-account.qmd
          - text: "Optional: Positron installation (for R)"
            #href: s4-positron-install.qmd
      - text: Other
        menu: 
          - text: Practical Workshop Info
            href: o1-practical.qmd
          - text: "---------------"
          - text: Further Resources
            href: o2-resources.qmd
    tools:
      - icon: github
        aria-label: "The GitHub repo for this website"
        menu:
          - text: Source Code
            url:  https://github.com/cfaes-bioinfo/agentic-ai-workshop
          - text: Report an Issue
            url:  https://github.com/cfaes-bioinfo/agentic-ai-workshop/issues/new?template=Blank+issue
  page-footer:
    left: |
      2026, Jelmer Poelstra, [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)   ![](http://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc.png){width="10%"}
    center: |
      ![](/img/CFAES-Horiz-RGBHEX.svg){width="40%"}
    right:
      - icon: github
        href: https://github.com/cfaes-bioinfo/agentic-ai-workshop
        aria-label: "The GitHub repo for this website"
format:
  html:
    theme:
      - cosmo
      - brand
    highlight-style: atom-one
    css: styles.css
    toc: true
    number-sections: true
    number-depth: 3
    grid:
      body-width: 800px

execute:
  freeze: auto
  engine: knitr
  eval: true
editor: source

knitr:
  opts_chunk:
    class-output: regular-r-output
    class-message: regular-r-output
    class-warning: warning-r-output
    class-error: error-r-output
