---
number-sections: false
toc: false
format:
  html:
    grid:
      body-width: 900px
---

<h4 align="center">

<span style="font-size:34px; color:#bb0000">**Using Generative and Agentic AI <br> for Omics Data Analysis**</span><br>
<span style="font-size:22px; color:#3f4443; display:inline-block; margin-top:8px;">An Ohio State workshop on July 13–14, 2026</span>

</h4>
<hr style="width:30%; margin:-35px auto 0 auto; border:1px solid #3f4443;">

<hr style="height:1pt; visibility:hidden;" />

::: {.panel-tabset}

### Day 1: Monday

| Section | Time | Instructor | Topic & link |
|:-:|----|---|------------|
| 1 | 09:00 am -- 09:45 am | _all_ | [Intro to the workshop](./01-workshop-intro.qmd) |
| 2 | 09:45 am -- 10:45 am | Menuka | [Intro to Generative AI and LLMs](./02-ai-intro.qmd) |
|  | [*10:45 am -- 11:00 am*]{style="color:steelblue"} |  | ☕️ [*Break*]{style="color:steelblue"} |
| 3 | 11:00 am -- 11:30 am | Derek Ditmer, OTDI | [Approved genAI Tools at OSU](./03-osu-approved.qmd) |
| 4 | 11:30 am -- 12:15 pm | Jonathan | [GenAI use cases and tools for research](./04-genai-use-cases.pdf) |
|  | [*12:15 pm -- 01:00 pm*]{style="color:steelblue"} |  | 🍽 [*Lunch*]{style="color:steelblue"} |
| 5 | 01:00 pm -- 02:30 pm | Jelmer | [OSC and VS Code setup](./05-setup.qmd) |
|  | [*02:30 pm -- 02:45 pm*]{style="color:steelblue"} |  | ☕️ [*Break*]{style="color:steelblue"} |
| 6 | 02:45 pm -- 03:30 pm | Jelmer | [Code completions with GitHub Copilot](./06-copilot.qmd) |
| 7 | 03:30 pm -- 04:00 pm | Evan Jaffe, OSC | [AI applications at OSC](./07-osc-ai.pdf) |

: {.striped .hover tbl-colwidths="[5, 22, 20, 53]"}

### Day 2: Tuesday

| Section | Time | Instructor | Topic & link |
|:-:|----|---|------------|
| 6 | 09:00 am -- 09:45 am | Jelmer | [Code completions with GitHub Copilot](./06-copilot.qmd) (cont.) |
| 8 | 09:45 am -- 10:45 am | Jelmer | [Agentic chat with Claude Code](./08-claude.qmd) |
|  | [*10:45 am -- 11:00 am*]{style="color:steelblue"} |  | ☕️ [*Break*]{style="color:steelblue"} |
| 9 | 11:00 am -- 11:45 am | Hannah | Prompt engineering: [slides](./09-prompts-slides.qmd) and [page](./09-prompts-page.qmd) |
| 10 | 11:45 am -- 12:15 pm | Menuka | [Advanced agentic options and skills](./10-agentic2.qmd) |
|  | [*12:15 pm -- 01:00 pm*]{style="color:steelblue"} |  | 🍽 [*Lunch*]{style="color:steelblue"} |
| 10 | 01:00 pm -- 01:30 pm | Menuka | [Advanced agentic options and skills](./10-agentic2.qmd) (cont.) |
| 11 | 01:30 pm -- 02:00 pm | Hannah | [Limitations and responsible use of AI](./11-responsible-use.qmd) |
| 12 | 02:00 pm -- 03:30 pm | *all* | [DIY with own (or other) data](./12-diy.qmd) |
| 13 | 03:30 pm -- 04:00 pm | *all* | [Concluding remarks](./13-concluding.qmd) |

: {.striped .hover tbl-colwidths="[5, 22, 20, 53]"}

:::

<hr style="height:1pt; visibility:hidden;" />
